import 'package:firebase_core/firebase_core.dart';
import 'package:flutter/material.dart';
import 'package:spotit/features/complaints/presentation/pages/home_page.dart';
import 'firebase_options.dart'; // This file is generated by flutterfire configure

void main() async {
  WidgetsFlutterBinding.ensureInitialized();
  try {
    await Firebase.initializeApp(
      options: DefaultFirebaseOptions.currentPlatform,
    );
  } catch (e) {
    // Fallback if DefaultFirebaseOptions is not available yet (user setup required)
    debugPrint(
      'Firebase initialization failed: $e. Make sure to run flutterfire configure.',
    );
    // In a real app we might want to show an error screen or initialize with default values if possible
    // For now we will try to initialize without options if that fails (though options are usually required)
    try {
      await Firebase.initializeApp();
    } catch (e) {
      debugPrint('Firebase initialization without options failed: $e');
    }
  }

  runApp(const SpotItApp());
}

class SpotItApp extends StatelessWidget {
  const SpotItApp({super.key});

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'SpotIT',
      theme: ThemeData(
        colorScheme: ColorScheme.fromSeed(seedColor: Colors.blue),
        useMaterial3: true,
      ),
      home: const HomeScreen(),
    );
  }
}
